apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-ec-pvc
  namespace: rook-ceph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-ceph-block-ec