apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-my-store
  namespace: rook-ceph
  labels:
    app: rook-ceph-rgw
    rook_object_store: my-store
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: rook-ceph-rgw
    rook_object_store: my-store